[package]
name = "embed"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "29.0.1"
wlug = { git = "https://github.com/serd223/wlug.git", rev = "f1eede43654c77ee25da8da5ded142023f3f075d", version = "0.1.0" }
